"""
Django settings for zero project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5a%uxnh$cwg9=+bc592lu-8%tm+61pv7kn5raq=r7=2x=f4!-0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'crispy_forms',
    # 'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    # 'numpy',
    'litmus',

]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zeroth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'litmus/templates/litmus') ],  # Bases Templates Directory 추가
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zeroth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Import secret keys in secrets.json
from django.core.exceptions import ImproperlyConfigured
 
with open("static/secret/secrets.json") as f:
    secrets = json.loads(f.read())
 
def get_secret(setting, secrets=secrets):
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {0} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)
 
SECRET_KEY = get_secret("SECRET_KEY")

# Microsoft Azure Active Directory
AZUREAD_OAUTH2_KEY = get_secret("AZUREAD_OAUTH2_KEY")
AZUREAD_OAUTH2_SECRET = get_secret("AZUREAD_OAUTH2_SECRET")
AZUREAD_OAUTH2_RESOURCE = 'https://graph.windows.net' # https://graph.windows.net or https://<your Sharepoint site name>-my.sharepoint.com.

AZUREAD_TENANT_OAUTH2_KEY = get_secret("AZUREAD_OAUTH2_KEY")
AZUREAD_TENANT_OAUTH2_SECRET = get_secret("AZUREAD_OAUTH2_SECRET")
AZUREAD_TENANT_OAUTH2_TENANT_ID = get_secret("AZUREAD_OAUTH2_TENANT_ID")
AZUREAD_TENANT_OAUTH2_RESOURCE = 'https://graph.windows.net'

MCSCIENCE_SHAREPOINT_GROUP_ID = get_secret("MCSCIENCE_SHAREPOINT_GROUP_ID")
MCSCIENCE_SHAREPOINT_ETUDE_TEAMSITE_ID = get_secret("MCSCIENCE_SHAREPOINT_ETUDE_TEAMSITE_ID")
MCSCIENCE_SHAREPOINT_ETUDE_EXCEL_DRIVE_ID = get_secret("MCSCIENCE_SHAREPOINT_ETUDE_EXCEL_DRIVE_ID")
MCSCIENCE_SHAREPOINT_ETUDE_EXCEL_LIST_ID = get_secret("MCSCIENCE_SHAREPOINT_ETUDE_EXCEL_LIST_ID")

GOOGLE_MAPS_API_KEY_LITMUS =  get_secret("GOOGLE_MAPS_API_KEY_LITMUS")
